---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
  network:
    - ["private_network", {ip: "33.33.33.11"}]
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    # data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[eas-nfs::default]
    attributes:
      rsyslog:
        server_ip: "33.33.33.10"
